image: python:3-bullseye

stages:
- test
- bdist
- upload

.tox:  &tox
  stage: test
  variables:
    TOXENV: $CI_JOB_NAME
  before_script:
  - pip install tox
  script:
  - export TOXENV=${TOXENV:-$CI_JOB_NAME}
  - echo TOXENV=$TOXENV
  - tox
  artifacts:
    paths:
    - coverage-*.xml
    - xunit-*.xml
    expire_in: 1 day

flake8:
  <<: *tox

black:
  <<: *tox

isort:
  <<: *tox

linux:
  <<: *tox
  before_script:
  - apt update && apt -y --no-install-recommends install xvfb xauth
  - pip install tox
  artifacts:
    paths:
    - coverage-*.xml
    - xunit-*.xml
    expire_in: 1 day

win32:
  before_script:
  - choco install python3 --no-progress --version=3.7.9 -y -f --forcex86 --source "'https://nexus.ikus-soft.com/repository/choco/'"
  - $Env:path += ";C:\Python37\Scripts\;C:\Python37\;"
  - $Env:path
  - python.exe -VV
  - pip.exe install tox
  script:
  - tox.exe
  stage: test
  tags:
  - windows
  artifacts:
    paths:
    - coverage-*.xml
    - xunit-*.xml
    expire_in: 1 day

macos:
  script:
  - tox
  stage: test
  tags:
  - macos
  artifacts:
    paths:
    - coverage-*.xml
    - xunit-*.xml
    expire_in: 1 day

bdist:py3: 
  stage: bdist
  needs: []
  script:
  - pip3 install wheel
  - python3 setup.py sdist bdist_wheel
  dependencies: []
  artifacts:
    paths:
    - dist/*.whl

upload:sonar:
  stage: upload
  needs:
  - linux
  - macos
  - win32
  image: sonarsource/sonar-scanner-cli
  variables:
    SONAR_PROJECT_BASE_DIR: "${CI_PROJECT_DIR}"
  script:
  - sonar-scanner -X -Dsonar.python.coverage.reportPaths=coverage-*.xml -Dsonar.python.xunit.reportPaths=xunit-*.xml -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.projectVersion=$(git describe) -Dsonar.qualitygate.wait=true

upload:wheel:
  stage: upload
  only:
    variables:
      - $NEXUS_USR
      - $NEXUS_PWD
      - $NEXUS_PYPI_URL
  script: |
    set -x
    # Publish wheel
    pip3 install wheel twine readme_renderer[md] --upgrade
    LANG="C.UTF-8" python3 -m readme_renderer README.md -o /tmp/README.html
    twine upload dist/*.whl -u $NEXUS_USR -p $NEXUS_PWD --repository-url $NEXUS_PYPI_URL
    if [[ -z "$CI_COMMIT_TAG" ]]; then
      twine upload dist/*.whl -u $PYPI_USR -p $PYPI_PWD
    fi